Clean script with shellCheck analysis

diff --git a/dlScan b/dlScan
--- a/dlScan
+++ b/dlScan
@@ -1,24 +1,24 @@
 #!/usr/local/bin/bash
 
-exe=$(echo $0 | sed "s/.*\\/\(.*\)/\\1/g")
+exe="$(echo "$0" | sed 's/.*\\/\(.*\)/\\1/g')"
 path=$(pwd)
 
 usage() {
-	echo "usage: ${exe} manga_name [scan_number=latest] [path=.]" >&2
+    echo "usage: ${exe} manga_name [scan_number=latest] [path=.]" >&2
 }
 
 if [[ -z "${1}" ]]; then
-	usage
-	exit 1
+    usage
+    exit 1
 fi
 
 if [[ ! -z "${3}" ]]; then
-	if [[ -d "${3}" ]]; then
-		path="${3}"
-	else
-		echo "${exe}: ${3}: Not a directory" >&2
-		exit 1
-	fi
+    if [[ -d "${3}" ]]; then
+        path="${3}"
+    else
+        echo "${exe}: ${3}: Not a directory" >&2
+        exit 1
+    fi
 fi
 
 declare -A aliases
@@ -84,7 +84,7 @@ name=$(echo "${1}" | sed "s/[ -_.'\"\(\)\{\}\[\]]//g" | tr '[:upper:]' '[:lower:
 name="${aliases[${name}]}"
 
 if [[ -z "${name}" ]]; then
-	name="${1}"
+    name="${1}"
 fi
 
 skip_nbr=2
@@ -100,20 +100,20 @@ urls=("http://cdn.japscan.com/lel/\${name}/\${chapter}/\${n}.\${ext[\$ex]}"\
       "http://cdn.japscan.com/lel/\${name}/\${chapter}/RAW-\${n2}.\${ext[\$ex]}")
 
 latest() {
-	arg=$(echo "${1}" | tr '[:upper:]' '[:lower:]' | sed "s/ /-/g")
-	last=$(curl -s "http://www.japscan.com/mangas/${arg}/" 2>/dev/null | grep "//www.japscan.com/lecture-en-ligne/${arg}/" | head -n 2 | tail -n 1 | sed "s/.*href=\"[^\"]*\/\([0-9]*\)\/\".*/\1/")
-	echo $last
+    arg=$(echo "${1}" | tr '[:upper:]' '[:lower:]' | sed "s/ /-/g")
+    last=$(curl -s "http://www.japscan.com/mangas/${arg}/" 2>/dev/null | grep "//www.japscan.com/lecture-en-ligne/${arg}/" | head -n 2 | tail -n 1 | sed "s/.*href=\"[^\"]*\/\([0-9]*\)\/\".*/\1/")
+    echo $last
 }
 
 chapter="${2}"
 
 if [[ -z "${2}" ]] || ! [[ "${2}" =~ ^[0-9]*$ ]]; then
-	chapter=$(latest "${name}")
+    chapter=$(latest "${name}")
 fi
 
 if [[ -d "${path}/${name}/${chapter}" ]]; then
-	echo "Chapter n°${chapter} of ${name} already downloaded."
-	exit 0
+    echo "Chapter n°${chapter} of ${name} already downloaded."
+    exit 0
 fi
 
 i=0
@@ -124,57 +124,57 @@ dl=0
 
 exists=1
 while [[ $exists -eq 1 ]]; do
-	mkdir -p "${path}/${name}/${chapter}"
-	n=$(printf "%02d" $i)
-	n2=$(printf "%03d" $i)
-	if [[ $double -eq 1 ]]; then
-		n="${n}"-$(printf "%02d" $(( $i + 1)))
-	fi
-	curl -s "$(eval echo "${urls[$n_url]}" | sed "s/ /%20/g")" > "${path}/${name}/${chapter}/${n}.${ext[$ex]}"
-	test=$(echo $(wc -c "${path}/${name}/${chapter}/${n}.${ext[$ex]}") | cut -d\  -f 1)
-	if [[ $test -lt 1000 ]]; then
-		rm -f "${path}/${name}/${chapter}/${n}.${ext[$ex]}"
-		ex=$(( $ex + 1 ))
-		if [[ $ex -ge ${#ext[@]} ]]; then
-			double=$(( 1 - $double ))
-			if [[ $double -eq 0 ]]; then
-				n_url=$(( $n_url + 1 ))
-				if [[ $n_url -ge ${#urls[@]} ]]; then
-					skip=$(( $skip + 1 ))
-					i=$(( i + 1 ))
-					n_url=0
-					if [[ $skip -gt $skip_nbr ]]; then
-						exists=0
-					fi
-				fi
-			fi
-			ex=0
-		fi
-	else
-		echo "Download $(eval echo "${urls[$n_url]}")"
-		if [[ $double -eq 1 ]]; then
-			i=$(( $i + 1 ))
-		fi
-		ex=0
-		double=0
-		skip=0
-		dl=$(( $dl + 1 ))
-	fi
-	if [[ $exists -eq 0 ]]; then
-		if [[ $dl -eq 0 ]]; then
-			rm -rf "${path}/${name}/${chapter}"
-			echo "Scan ${name} n°${chapter} not found"
-			n=$(ls -1 "${path}/${name}" | wc -l)
-			if [[ $n -eq 0 ]]; then
-				rm -rf "${path}/${name}"
-			fi
-		else
-			echo "Downloaded $dl images from ${name} n°${chapter} to :"
-			echo "${path}/${name}/${chapter}/*"
-		fi
-	fi
-	if [[ $test -gt 1000 ]]; then
-		i=$(( $i + 1 ))
-	fi
+    mkdir -p "${path}/${name}/${chapter}"
+    n=$(printf "%02d" $i)
+    n2=$(printf "%03d" $i)
+    if [[ $double -eq 1 ]]; then
+        n="${n}"-$(printf "%02d" $(( i + 1)))
+    fi
+    curl -s "$(eval echo "${urls[$n_url]}" | sed "s/ /%20/g")" > "${path}/${name}/${chapter}/${n}.${ext[$ex]}"
+    count_chars="$(wc -c "${path}/${name}/${chapter}/${n}.${ext[$ex]}")" | cut -d\  -f 1
+    if [[ $count_chars -lt 1000 ]]; then
+        rm -f "${path}/${name}/${chapter}/${n}.${ext[$ex]}"
+        ex=$(( ex + 1 ))
+        if [[ $ex -ge ${#ext[@]} ]]; then
+            double=$(( 1 - double ))
+            if [[ $double -eq 0 ]]; then
+                n_url=$(( n_url + 1 ))
+                if [[ $n_url -ge ${#urls[@]} ]]; then
+                    skip=$(( skip + 1 ))
+                    i=$(( i + 1 ))
+                    n_url=0
+                    if [[ $skip -gt $skip_nbr ]]; then
+                        exists=0
+                    fi
+                fi
+            fi
+            ex=0
+        fi
+    else
+        echo "Download $(eval echo "${urls[$n_url]}")"
+        if [[ $double -eq 1 ]]; then
+            i=$(( i + 1 ))
+        fi
+        ex=0
+        double=0
+        skip=0
+        dl=$(( dl + 1 ))
+    fi
+    if [[ $exists -eq 0 ]]; then
+        if [[ $dl -eq 0 ]]; then
+            rm -rf "${path:?}/${name}/${chapter}"
+            echo "Scan ${name} n°${chapter} not found"
+            n=$(find "${path}/${name}" | wc -l)
+            if [[ $n -eq 0 ]]; then
+                rm -rf "${path:?}/${name}"
+            fi
+        else
+            echo "Downloaded $dl images from ${name} n°${chapter} to :"
+            echo "${path}/${name}/${chapter}/*"
+        fi
+    fi
+    if [[ $count_chars -gt 1000 ]]; then
+        i=$(( i + 1 ))
+    fi
 done
 
